# Generated by Django 2.1.5 on 2020-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200812_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPresident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('member_name', models.CharField(max_length=200)),
                ('message_title', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(default='01-01-2001'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to='media/images/club_pic/logo'),
        ),
        migrations.AlterField(
            model_name='usermembers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userstaffs',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
