# Generated by Django 2.1.5 on 2020-08-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200817_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
