# Generated by Django 2.1.5 on 2020-08-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200817_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='dob',
            field=models.DateField(default='1998-01-01'),
        ),
    ]
